#PATIENT, DOCTOR 그리고 APPOINTMENT 테이블에서 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회하는 SQL문을 작성해주세요. 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시 항목이 출력되도록 작성해주세요. 결과는 진료예약일시를 기준으로 오름차순 정렬해주세요.

# SELECT
# a.APNT_NO,
# p.PT_NAME,
# p.PT_NO,
# a.MCDP_CD,
# d.DR_NAME,
# a.APNT_YMD
# FROM
# PATIENT p
# JOIN APPOINTMENT a
# ON p.PT_NO = a.PT_NO
# JOIN DOCTOR d
# ON d.DR_ID = a.MDDR_ID
# WHERE DATE_FORMAT(a.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND a.MCDP_CD = "CS" AND a.APNT_CNCL_YN != "Y"
# ORDER BY APNT_YMD;

-- 코드를 입력하세요
SELECT APPOINTMENT.APNT_NO, PATIENT.PT_NAME, PATIENT.PT_NO,
    APPOINTMENT.MCDP_CD, DOCTOR.DR_NAME, APPOINTMENT.APNT_YMD
FROM PATIENT

JOIN APPOINTMENT
ON PATIENT.PT_NO = APPOINTMENT.PT_NO

RIGHT JOIN DOCTOR
ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID

WHERE APPOINTMENT.APNT_CNCL_YN = "N" and APPOINTMENT.MCDP_CD = 'cs'
and DATE_FORMAT(APPOINTMENT.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND APPOINTMENT.MCDP_CD = "CS" AND APPOINTMENT.APNT_CNCL_YN != "Y"

ORDER BY APPOINTMENT.APNT_YMD


