#USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.
-- 코드를 입력하세요

# SELECT (
#     SELECT b.WRITER_ID, sum(b.PRICE) as total FROM USED_GOODS_BOARD as b
#     WHERE STATUS LIKE "DONE"
#     GROUP BY b.WRITER_ID
#     HAVING total>700000), u.NICKNAME FROM USED_GOODS_BOARD as b
# JOIN USED_GOODS_USER u
# ON b.WRITER_ID = u.USER_ID
# WHERE b.STATUS LIKE "DONE"
# GROUP BY b.WRITER_ID

SELECT subquery.WRITER_ID as USER_ID, u.NICKNAME, subquery.TOTAL_SALES
FROM (
    SELECT b.WRITER_ID, SUM(b.PRICE) AS TOTAL_SALES 
    FROM USED_GOODS_BOARD AS b
    WHERE STATUS LIKE 'DONE'
    GROUP BY b.WRITER_ID
    HAVING TOTAL_SALES >= 700000
) AS subquery
JOIN USED_GOODS_USER AS u 
ON subquery.WRITER_ID = u.USER_ID
ORDER BY TOTAL_SALES ASC